export const CONFIG = {
    CELL_SIZE: 20,
    RESEARCH_DURATION: 100,
    CONSTRUCTION_TIME: 135,
    FOCUS_DURATION: 70,
    TICK_RATE: 1000,
    SPEEDS: [0, 1, 3, 5],
    INITIAL_DATE: new Date(1936, 0, 1, 12, 0),
    MAP_PATH: 'assets/maps/europe_1936.json',
    MAX_TECH_LEVEL: 5,
    UNIT_MAINTENANCE_MULTIPLIER: 1.0,
    PRODUCTION_PER_FACTORY: 1.5,
    MANPOWER_USAGE_PERCENT: 0.05
};
